apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-ticket-reservation
  labels:
    app: train-ticket-reservation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-ticket-reservation
  template:
    metadata:
      labels:
        app: train-ticket-reservation
    spec:
      containers:
        - name: ticket-app
          image: kasiviswanadh-raga/train-ticket-reservation:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"

