apiVersion: v1
kind: Service
metadata:
  name: train-ticket-service
spec:
  type: LoadBalancer
  selector:
    app: train-ticket-reservation   # âœ… MATCHES DEPLOYMENT
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
