apiVersion: v1
kind: Service
metadata:
  name: train-ticket-service
  labels:
    app: train-ticket-reservation
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: http
  selector:
    app: train-ticket-reservation
